### ISSUE TITLE
More details needed with the existing isntructions

### ISSUE THREAD

**Issue by ovizii** [ndarilek/hugo-sandstorm#4]
So I installed Hugo into my sandstorm instance, created a new Hugo grain and I now get instructions to:

To check out the Git repository containing your site, first add an authorization key to Git: 
_...
and 
Then run the following to start with a fresh site:
..._

Now I am wondering where to run these commands? At this point in time, I would like to create a new site, I don't have any site and no git repository. 

I checked for apps on sandstorm that could work and found: Gogs, Gitweb and GitLab. Would I be able to run any of these 3 on the same Sandstorm instance and host my Hugo website code there?

**Comment by ocdtrekkie** [comment]
The Hugo app is your Git repository. The instructions in the app are to clone it to your computer so you can edit it.

**Comment by ovizii** [comment]
ok, thanks, starting to make slightly more sense to me :-) 
so without having a linux pc somewhere to use git I can't use Hugo? 

Found this part in its description, hence my question (I was wondering about the web-based interface I couldn't find):

> Updates and themes can be pushed directly to an embedded Git repository, or can be edited via a web-based administrative interface.

**Comment by ocdtrekkie** [comment]
Git should work on a Windows PC or Mac, I am unsure if the commands will work as-is on other platforms as I didn't test it and don't know Git well. The web-based administrative interface has some bugs. It's useful, but for instance, right now editing your config file in the web-based interface will break your site.

**Comment by ovizii** [comment]
Thanks for the pointers, I'll do some more reading up :-)
