### ISSUE TITLE
git remote address and password keep changing

### ISSUE THREAD

**Issue by fgiorlando** [ndarilek/hugo-sandstorm#5]
Thanks for porting hugo, it looks like a really nice engine.
I have been playing about with it a little and am having some difficulties.
The remote address for pushing git changes seems to change each time the grain is used.
Shouldn't this stay the same?

**Comment by ocdtrekkie** [comment]
The old one will continue to work, but it'll always offer a new one.

**Comment by ndarilek** [comment]
Right, these change every 5 minutes, and are rotated by Sandstorm itself. If you use one within 5 minutes then it will continue to work, and it shows up on your Web Keys page along with its creation date, where it can be revoked if you like.
